name: website deployment
on: [push]
jobs:
 deploy:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@master
    - name: deploy website to testing.com
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.KEY }}
      with:
        source: '.'
        target: '/var/www/html/'
        strip_components: 1
